### ISSUE TITLE
Decrypted file is corruped 

### ISSUE THREAD

**Issue by andriyohorodnyk** [apalkovskiy/demo_aes#1]
file after encryption and decryption is not identical to original file
please fix this

**Comment by apalkovskiy** [comment]
Should we get the same file as it was originally file or file with our
added header?
because I added the header,
if we need to get the same file, I'll do it now.

чт, 5 нояб. 2020 г. в 17:27, Andriy <notifications@github.com>:

**Comment by apalkovskiy** [comment]
I did it, now we will get the same file like we have had till encrypt

чт, 5 нояб. 2020 г. в 18:06, Pavel apal <apalkovskiy@gmail.com>:
